version: 2.1
orbs:
  node: circleci/node@1.1.6
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  checkout:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - persist_to_workspace:
                root: ~/
                paths:
                  - project
  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - node/with-cache:
          steps:
            - run: npm test
  build:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - attach_workspace:
                at: ~/
            - run: npm run build
            - run: ls -la
            - persist_to_workspace:
                root: ~/
                paths:
                  - project
  publish:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: ~/
      - run: ls -la
      - azure-cli/login-with-service-principal
      - run:
          name: publish dist folder
          command: az storage blob upload-batch -s dist -d \$web --account-name kdluizpereira

workflows:
  build-and-test:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
