version: 2.1
orbs:
  node: circleci/node@1.1.6
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    executor:
      name: azure-cli/default
    steps:
      - azure-cli/install
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  publish:
    executor: azure-cli/azure-docker
    steps:
      - azure-cli/login-with-service-principal
      - run:
          command: az resource list
          name: List resources of tenant stored as `AZURE_SP_TENANT` env var
workflows:
  build-and-test:
    jobs:
      - publish
      - test
      - build:
          requires:
            - test
