version: 2.1
orbs:
  node: circleci/node@1.1.6
  azure-cli: circleci/azure-cli@1.1.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  publish:
    executor: azure-cli/azure-docker
    steps:
      - attach_workspace:
          at: ~/
      - azure-cli/login-with-service-principal
      - run:
          name: publish dist folder
          command: az storage blob upload-batch -s ./build/dist -d \$web --account-name kdluizpereira

workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
